src/Entity/OrderLine.php
<?php

namespace Prolyfix\ProcurementBundle\Entity;

use App\Entity\TimeData;
use Prolyfix\ProcurementBundle\Repository\OrderLineRepository;
use Doctrine\ORM\Mapping as ORM;
use Prolyfix\ProcurementBundle\Entity\Order;
use Prolyfix\ProcurementBundle\Entity\Product;

#[ORM\Entity(repositoryClass: OrderLineRepository::class)]
class OrderLine extends TimeData
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orderLines')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $procurementOrder = null;

    #[ORM\ManyToOne(inversedBy: 'orderLines')]
    private ?Product $product = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $orderLine = null;

    #[ORM\Column(nullable: true)]
    private ?float $quantity = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $measure = null;

    #[ORM\Column(nullable: true)]
    private ?float $grossPrice = null;

    #[ORM\Column(nullable: true)]
    private ?float $vat = null;

    #[ORM\Column(nullable: true)]
    private ?float $netPrice = null;

    public function __contruct()
    {
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProcurementOrder(): ?Order
    {
        return $this->procurementOrder;
    }

    public function setProcurementOrder(?Order $procurementOrder): static
    {
        $this->procurementOrder = $procurementOrder;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getOrderLine(): ?string
    {
        return $this->orderLine;
    }

    public function setOrderLine(?string $orderLine): static
    {
        $this->orderLine = $orderLine;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(?float $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getMeasure(): ?string
    {
        return $this->measure;
    }

    public function setMeasure(?string $measure): static
    {
        $this->measure = $measure;

        return $this;
    }

    public function getGrossPrice(): ?float
    {
        return $this->grossPrice;
    }

    public function setGrossPrice(?float $grossPrice): static
    {
        $this->grossPrice = $grossPrice;

        return $this;
    }

    public function getPrice(): float
    {
        return $this->getQuantity() * $this->getGrossPrice();
    }

    public function getVat(): ?float
    {
        return $this->vat;
    }

    public function setVat(?float $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    public function getNetPrice(): ?float
    {
        return $this->netPrice;
    }

    public function setNetPrice(?float $netPrice): static
    {
        $this->netPrice = $netPrice;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace Prolyfix\ProcurementBundle\Entity;

use App\Attribute\SearchableEntity;
use App\Attribute\SearchableField;
use App\Entity\Commentable;
use Prolyfix\ProcurementBundle\Entity\Inventar;
use Prolyfix\ProcurementBundle\Entity\OrderLine;
use App\Entity\TimeData;
use App\Entity\Trait\AvatarTrait;
use App\Entity\Trait\CommentsTrait;
use App\Entity\Trait\MediaTrait;
use Prolyfix\ProcurementBundle\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[SearchableEntity(controller: 'Prolyfix\ProcurementBundle\Controller\ProductCrudController')]
class Product extends Commentable
{
    use AvatarTrait;


    #[ORM\Column(length: 255)]
    #[SearchableField]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;



    /**
     * @var Collection<int, Order>
     */
    #[ORM\ManyToMany(targetEntity: Order::class, mappedBy: 'products')]
    private Collection $orders;

    /**
     * @var Collection<int, Receipt>
     */
    #[ORM\ManyToMany(targetEntity: Receipt::class, mappedBy: 'products')]
    private Collection $receipts;

    /**
     * @var Collection<int, OrderLine>
     */
    #[ORM\OneToMany(targetEntity: OrderLine::class, mappedBy: 'product')]
    private Collection $orderLines;

    /**
     * @var Collection<int, Inventar>
     */
    #[ORM\OneToMany(targetEntity: Inventar::class, mappedBy: 'product')]
    private Collection $inventars;

    #[ORM\Column(nullable: true)]
    private ?bool $isSprechstundenbedarf = null;

    #[ORM\Column(nullable: true)]
    private ?bool $hasExpirationDate = null;

    #[ORM\Column]
    private ?float $minimalQuantity = null;


    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->receipts = new ArrayCollection();
        $this->orderLines = new ArrayCollection();
        $this->inventars = new ArrayCollection();
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }



    public function __toString(): string
    {
        return $this->name;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->addProduct($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            $order->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Receipt>
     */
    public function getReceipts(): Collection
    {
        return $this->receipts;
    }

    public function addReceipt(Receipt $receipt): static
    {
        if (!$this->receipts->contains($receipt)) {
            $this->receipts->add($receipt);
            $receipt->addProduct($this);
        }

        return $this;
    }

    public function removeReceipt(Receipt $receipt): static
    {
        if ($this->receipts->removeElement($receipt)) {
            $receipt->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderLine>
     */
    public function getOrderLines(): Collection
    {
        return $this->orderLines;
    }

    public function addOrderLine(OrderLine $orderLine): static
    {
        if (!$this->orderLines->contains($orderLine)) {
            $this->orderLines->add($orderLine);
            $orderLine->setProduct($this);
        }

        return $this;
    }

    public function removeOrderLine(OrderLine $orderLine): static
    {
        if ($this->orderLines->removeElement($orderLine)) {
            // set the owning side to null (unless already changed)
            if ($orderLine->getProduct() === $this) {
                $orderLine->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Inventar>
     */
    public function getInventars(): Collection
    {
        return $this->inventars;
    }

    public function addInventar(Inventar $inventar): static
    {
        if (!$this->inventars->contains($inventar)) {
            $this->inventars->add($inventar);
            $inventar->setProduct($this);
        }

        return $this;
    }

    public function removeInventar(Inventar $inventar): static
    {
        if ($this->inventars->removeElement($inventar)) {
            // set the owning side to null (unless already changed)
            if ($inventar->getProduct() === $this) {
                $inventar->setProduct(null);
            }
        }

        return $this;
    }

    public function isSprechstundenbedarf(): ?bool
    {
        return $this->isSprechstundenbedarf??false;
    }

    public function setIsSprechstundenbedarf(?bool $isSprechstundenbedarf): static
    {
        $this->isSprechstundenbedarf = $isSprechstundenbedarf;

        return $this;
    }

    public function hasExpirationDate(): ?bool
    {
        return $this->hasExpirationDate;
    }

    public function setHasExpirationDate(?bool $hasExpirationDate): static
    {
        $this->hasExpirationDate = $hasExpirationDate;

        return $this;
    }

    public function getMinimalQuantity(): ?float
    {
        return $this->minimalQuantity;
    }

    public function setMinimalQuantity(float $minimalQuantity): static
    {
        $this->minimalQuantity = $minimalQuantity;

        return $this;
    }
}

templates/product/detail.html.twig
{% extends '@!EasyAdmin/page/content.html.twig' %}
{% block main %}
	<div
		class="container-fluid">
		<!-- start page title -->
		<div class="row">
			<div class="col-12">
				<div class="page-title-box">
					<h4 class="page-title">{{ entity.name}}</h4>
				</div>
			</div>
		</div>
		<!-- end page title -->

		<div class="row">
			<div
				class="col-xl-8 col-lg-7">
				<!-- project card -->
				<div class="card d-block">
					<div class="card-body">
						<div class="dropdown float-end">
							<a href="#" class="dropdown-toggle arrow-none text-muted" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="mdi mdi-dots-horizontal font-18"></i>
							</a>
							<div class="dropdown-menu dropdown-menu-end">
								<a href="
																																				                                                {{ea_url().setAction('edit', 'task', entity.instance.id)|raw}}" class="dropdown-item">
									<i class="mdi mdi-pencil-outline me-1"></i>Edit
								</a>
								<a href="javascript:void(0);" class="dropdown-item text-danger">
									<i class="mdi mdi-delete-outline me-1"></i>Delete
								</a>
							</div>
							<!-- end dropdown menu-->
						</div>
						<!-- end dropdown-->
						<div class="clearfix"></div>

						<h4>{{entity.instance.name}}</h4>

						<div class="row">
							<div
								class="col-md-8">
								<!-- assignee -->
								<p class="mt-2 mb-1 text-muted">{% trans %}Created by{% endtrans %}</p>
								<div class="d-flex align-items-start">
									{% include 'common/avatar.html.twig' with {'user': entity.instance.createdBy} %}
									<div class="w-100">
										<h5 class="mt-1 font-size-14">
											{{ entity.instance.createdBy.name }}
										</h5>
									</div>
								</div>
								<!-- end assignee -->
							</div>
							<div class="col-md-4">
								{% if entity.instance.avatarFilename is not null %}
									<img class="wt100" src="{{asset('/uploads/avatar/'~entity.instance.avatarFilename) | imagine_filter('avatar') }}" alt="Generic placeholder image">
								{% endif %}
							</div>
							<!-- end col -->
						</div>
						<!-- end row -->
						{% if entity.instance.description | length > 0 %}
							<h5 class="mt-3">{% trans %}Overview:{% endtrans %}</h5>

							<p class="text-muted mb-4">
								{{ entity.instance.description | raw}}
							</p>
						{% endif %}
						<!-- end sub tasks/checklists -->
					</div>
					<!-- end card-body-->
				</div>
				<div class="card d-block">
					<div class="card-body">
						<h4>{% trans %}
							lastOrders
							{% endtrans %}</h4>

						<div class="row">
							<div class="col-md-12">
								<table class="table table-condensed">
									<thead>
										<tr>
											<th>
												{% trans %}
												Date
												{% endtrans %}</th>
											<th>
												{% trans %}
												Quantity
												{% endtrans %}</th>
											<th>
												{% trans %}
												Price
												{% endtrans %}</th>
											<th>
												{% trans %}
												Lieferant
												{% endtrans %}</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
										{% for bestellung in bestellungen %}
											<tr>
												<td>{{ bestellung.procurementOrder.creationDate | date('d/m/Y') }}</td>
												<td>{{ bestellung.quantity }}</td>
												<td>{{ bestellung.price }}</td>
												<td>{{ bestellung.procurementOrder.thirdParty.name }}</td>
												<td>
													<a href="{{ ea_url().setAction('detail').setController('Prolyfix\\ProcurementBundle\\Controller\\OrderCrudController').setEntityId(bestellung.procurementOrder.id)|raw }}" class="btn btn-sm btn-primary">
														<i class="mdi mdi-eye"></i>
													</a>

												</td>
											</tr>
										{% endfor %}

									</tbody>
								</table>

							</div>
							<!-- end col -->
						</div>
						<!-- end row -->
					</div>
					<!-- end card-body-->
				</div>

				<!-- end card-->
				{% include 'section/comment/comments.html.twig' with {'comments': entity.instance.comments} %}
			</div>
			<div class="col-xl-4 col-lg-5">
				{% include 'admin/media/_mediaSidebar.html.twig' with {'entity': entity} %}
				{% include '@ProlyfixCrmBundle/thirdParty/_relatedCommentable.html.twig' with {'partners': partners, 'type': 'Product'} %}
			</div>
		</div>
		<!-- end row -->

	</div>
{% endblock %}